### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by akizzle** [l3uddz/plex_patrol#3]
Attempting to install on CentOS 7.

Filled out the values in the settings,ini.default however receiving the error below. 

[XXXX@localhost plex_patrol]$ sudo python patrol.py
Traceback (most recent call last):
  File "patrol.py", line 5, in <module>
    from utils import config
  File "/opt/plex_patrol/utils/config.py", line 4, in <module>
    SERVER_URL = config('SERVER_URL')
  File "/usr/lib/python2.7/site-packages/decouple.py", line 197, in __call__
    return self.config(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/decouple.py", line 85, in __call__
    return self.get(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/decouple.py", line 70, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SERVER_URL not found. Declare it as envvar or define a default value.

**Comment by l3uddz** [comment]
Did you rename the settings file without .default?

**Comment by akizzle** [comment]
Yep that did it! All is well TY
